"""add_offers_table

Revision ID: 0f30c29729ce
Revises: e8b1f2a9c4d7
Create Date: 2026-02-07 16:14:49.392045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f30c29729ce'
down_revision: Union[str, None] = 'e8b1f2a9c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('buyer_contact_id', sa.Integer(), nullable=True),
    sa.Column('parent_offer_id', sa.Integer(), nullable=True),
    sa.Column('offer_price', sa.Float(), nullable=False),
    sa.Column('earnest_money', sa.Float(), nullable=True),
    sa.Column('financing_type', sa.Enum('CASH', 'CONVENTIONAL', 'FHA', 'VA', 'HARD_MONEY', 'SELLER_FINANCING', 'OTHER', name='financingtype'), nullable=True),
    sa.Column('closing_days', sa.Integer(), nullable=True),
    sa.Column('contingencies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', name='offerstatus'), nullable=True),
    sa.Column('is_our_offer', sa.Boolean(), nullable=True),
    sa.Column('mao_low', sa.Float(), nullable=True),
    sa.Column('mao_base', sa.Float(), nullable=True),
    sa.Column('mao_high', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_property_id'), 'offers', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_property_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
