"""add property_id to conversation_history

Revision ID: 3f7222350efb
Revises: 0c7758a21c8d
Create Date: 2026-02-13 12:37:16.269796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7222350efb'
down_revision: Union[str, None] = '0c7758a21c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_history', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversation_history_property_id'), 'conversation_history', ['property_id'], unique=False)
    op.create_foreign_key(None, 'conversation_history', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_history', type_='foreignkey')
    op.drop_index(op.f('ix_conversation_history_property_id'), table_name='conversation_history')
    op.drop_column('conversation_history', 'property_id')
    # ### end Alembic commands ###
