"""initial schema

Revision ID: f838d6185616
Revises: 
Create Date: 2026-02-06 05:48:06.584527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f838d6185616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('user_source', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.Enum('TOOL_CALL', 'TOOL_RESULT', 'VOICE_COMMAND', 'SYSTEM_EVENT', name='activityeventtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'ERROR', name='activityeventstatus'), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_event_type'), 'activity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_events_id'), 'activity_events', ['id'], unique=False)
    op.create_index(op.f('ix_activity_events_timestamp'), 'activity_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_activity_events_tool_name'), 'activity_events', ['tool_name'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=True)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('compliance_rule_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('template_json', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rule_templates_id'), 'compliance_rule_templates', ['id'], unique=False)
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('LISTING', 'PURCHASE', 'DISCLOSURE', 'INSPECTION', 'LEASE', 'ADDENDUM', 'OTHER', name='contractcategory'), nullable=False),
    sa.Column('requirement', sa.Enum('REQUIRED', 'RECOMMENDED', 'OPTIONAL', name='contractrequirement'), nullable=True),
    sa.Column('docuseal_template_id', sa.String(length=100), nullable=True),
    sa.Column('docuseal_template_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('property_type_filter', sa.JSON(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('deal_type_filter', sa.JSON(), nullable=True),
    sa.Column('auto_attach_on_create', sa.Boolean(), nullable=True),
    sa.Column('auto_send', sa.Boolean(), nullable=True),
    sa.Column('default_recipient_role', sa.String(length=50), nullable=True),
    sa.Column('required_signer_roles', sa.JSON(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_templates_id'), 'contract_templates', ['id'], unique=False)
    op.create_index(op.f('ix_contract_templates_is_active'), 'contract_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_contract_templates_state'), 'contract_templates', ['state'], unique=False)
    op.create_table('deal_type_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('contract_templates', sa.JSON(), nullable=True),
    sa.Column('required_contact_roles', sa.JSON(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('compliance_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_type_configs_id'), 'deal_type_configs', ['id'], unique=False)
    op.create_index(op.f('ix_deal_type_configs_name'), 'deal_type_configs', ['name'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CONTRACT_SIGNED', 'NEW_LEAD', 'PROPERTY_PRICE_CHANGE', 'PROPERTY_STATUS_CHANGE', 'APPOINTMENT_REMINDER', 'SKIP_TRACE_COMPLETE', 'ENRICHMENT_COMPLETE', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('auto_dismiss_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_dismissed'), 'notifications', ['is_dismissed'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('research_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('PROPERTY_ANALYSIS', 'MARKET_RESEARCH', 'INVESTMENT_ANALYSIS', 'RISK_ASSESSMENT', 'DUE_DILIGENCE', 'CUSTOM', name='templatecategory'), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('research_type', sa.Enum('PROPERTY_ANALYSIS', 'MARKET_ANALYSIS', 'COMPLIANCE_CHECK', 'CONTRACT_ANALYSIS', 'OWNER_RESEARCH', 'NEIGHBORHOOD_ANALYSIS', 'CUSTOM', 'AI_RESEARCH', 'API_RESEARCH', name='researchtype'), nullable=False),
    sa.Column('ai_prompt_template', sa.Text(), nullable=True),
    sa.Column('ai_system_prompt', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_temperature', sa.String(length=10), nullable=True),
    sa.Column('ai_max_tokens', sa.Integer(), nullable=True),
    sa.Column('api_endpoints', sa.JSON(), nullable=True),
    sa.Column('research_parameters', sa.JSON(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('agent_expertise', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_templates_category'), 'research_templates', ['category'], unique=False)
    op.create_index(op.f('ix_research_templates_id'), 'research_templates', ['id'], unique=False)
    op.create_index(op.f('ix_research_templates_is_active'), 'research_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_research_templates_name'), 'research_templates', ['name'], unique=False)
    op.create_table('agent_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_preferences_id'), 'agent_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_agent_preferences_key'), 'agent_preferences', ['key'], unique=False)
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('applies_to_all_cities', sa.Boolean(), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_rule_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legal_citation', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('field_to_check', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('use_ai_fallback', sa.Boolean(), nullable=True),
    sa.Column('requires_document', sa.Boolean(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('document_description', sa.Text(), nullable=True),
    sa.Column('property_type_filter', sa.JSON(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_year_built', sa.Integer(), nullable=True),
    sa.Column('max_year_built', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('penalty_description', sa.Text(), nullable=True),
    sa.Column('fine_amount_min', sa.Float(), nullable=True),
    sa.Column('fine_amount_max', sa.Float(), nullable=True),
    sa.Column('how_to_fix', sa.Text(), nullable=True),
    sa.Column('estimated_fix_cost', sa.Float(), nullable=True),
    sa.Column('estimated_fix_time_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_checked', sa.Integer(), nullable=True),
    sa.Column('times_violated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_rule_id'], ['compliance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_category'), 'compliance_rules', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_rules_city'), 'compliance_rules', ['city'], unique=False)
    op.create_index(op.f('ix_compliance_rules_id'), 'compliance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_rules_is_active'), 'compliance_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_compliance_rules_rule_code'), 'compliance_rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_compliance_rules_state'), 'compliance_rules', ['state'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.Enum('HOUSE', 'APARTMENT', 'CONDO', 'TOWNHOUSE', 'LAND', 'COMMERCIAL', name='propertytype'), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'SOLD', 'RENTED', 'OFF_MARKET', name='propertystatus'), nullable=True),
    sa.Column('deal_type', sa.Enum('TRADITIONAL', 'SHORT_SALE', 'REO', 'FSBO', 'NEW_CONSTRUCTION', 'WHOLESALE', 'RENTAL', 'COMMERCIAL', name='dealtype'), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='conversationstatus'), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('tool_calls_count', sa.Integer(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('tool_calls_made', sa.JSON(), nullable=True),
    sa.Column('execution_trace', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['research_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_conversations_id'), 'agent_conversations', ['id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rules_checked', sa.Integer(), nullable=True),
    sa.Column('passed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('warning_count', sa.Integer(), nullable=True),
    sa.Column('completion_time_seconds', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('LAWYER', 'ATTORNEY', 'CONTRACTOR', 'INSPECTOR', 'APPRAISER', 'MORTGAGE_BROKER', 'LENDER', 'TITLE_COMPANY', 'BUYER', 'SELLER', 'TENANT', 'LANDLORD', 'PROPERTY_MANAGER', 'HANDYMAN', 'PLUMBER', 'ELECTRICIAN', 'PHOTOGRAPHER', 'STAGER', 'OTHER', name='contactrole'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('property_recaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('recap_text', sa.Text(), nullable=False),
    sa.Column('recap_context', sa.JSON(), nullable=False),
    sa.Column('voice_summary', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('last_trigger', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_recaps_id'), 'property_recaps', ['id'], unique=False)
    op.create_index(op.f('ix_property_recaps_property_id'), 'property_recaps', ['property_id'], unique=True)
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_type', sa.Enum('PROPERTY_ANALYSIS', 'MARKET_ANALYSIS', 'COMPLIANCE_CHECK', 'CONTRACT_ANALYSIS', 'OWNER_RESEARCH', 'NEIGHBORHOOD_ANALYSIS', 'CUSTOM', 'AI_RESEARCH', 'API_RESEARCH', name='researchtype'), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('endpoints_to_call', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='researchstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_id'), 'research', ['id'], unique=False)
    op.create_table('skip_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_first_name', sa.String(), nullable=True),
    sa.Column('owner_last_name', sa.String(), nullable=True),
    sa.Column('phone_numbers', sa.JSON(), nullable=True),
    sa.Column('emails', sa.JSON(), nullable=True),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('mailing_city', sa.String(), nullable=True),
    sa.Column('mailing_state', sa.String(), nullable=True),
    sa.Column('mailing_zip', sa.String(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skip_traces_id'), 'skip_traces', ['id'], unique=False)
    op.create_table('zillow_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('zpid', sa.Integer(), nullable=True),
    sa.Column('zestimate', sa.Float(), nullable=True),
    sa.Column('zestimate_low', sa.Float(), nullable=True),
    sa.Column('zestimate_high', sa.Float(), nullable=True),
    sa.Column('rent_zestimate', sa.Float(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('lot_area_units', sa.String(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('home_type', sa.String(), nullable=True),
    sa.Column('home_status', sa.String(), nullable=True),
    sa.Column('days_on_zillow', sa.Integer(), nullable=True),
    sa.Column('page_view_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('property_tax_rate', sa.Float(), nullable=True),
    sa.Column('annual_tax_amount', sa.Float(), nullable=True),
    sa.Column('hdp_url', sa.String(), nullable=True),
    sa.Column('zillow_url', sa.String(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('schools', sa.JSON(), nullable=True),
    sa.Column('tax_history', sa.JSON(), nullable=True),
    sa.Column('price_history', sa.JSON(), nullable=True),
    sa.Column('reso_facts', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zillow_enrichments_id'), 'zillow_enrichments', ['id'], unique=False)
    op.create_table('compliance_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('violation_message', sa.Text(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['compliance_checks.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_violations_id'), 'compliance_violations', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('docuseal_template_id', sa.String(), nullable=True),
    sa.Column('docuseal_submission_id', sa.String(), nullable=True),
    sa.Column('docuseal_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'IN_PROGRESS', 'PENDING_SIGNATURE', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'ARCHIVED', name='contractstatus'), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('required_by_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requirement_source', sa.Enum('AUTO_ATTACHED', 'MANUAL', 'AI_SUGGESTED', name='requirementsource'), nullable=True),
    sa.Column('requirement_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='todostatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='todopriority'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_table('contract_submitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('signing_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPENED', 'COMPLETED', 'DECLINED', name='submitterstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('docuseal_submitter_id', sa.String(), nullable=True),
    sa.Column('docuseal_submitter_slug', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_submitters_id'), 'contract_submitters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_submitters_id'), table_name='contract_submitters')
    op.drop_table('contract_submitters')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_compliance_violations_id'), table_name='compliance_violations')
    op.drop_table('compliance_violations')
    op.drop_index(op.f('ix_zillow_enrichments_id'), table_name='zillow_enrichments')
    op.drop_table('zillow_enrichments')
    op.drop_index(op.f('ix_skip_traces_id'), table_name='skip_traces')
    op.drop_table('skip_traces')
    op.drop_index(op.f('ix_research_id'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_property_recaps_property_id'), table_name='property_recaps')
    op.drop_index(op.f('ix_property_recaps_id'), table_name='property_recaps')
    op.drop_table('property_recaps')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_agent_conversations_id'), table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_compliance_rules_state'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_rule_code'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_is_active'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_id'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_city'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_category'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_index(op.f('ix_agent_preferences_key'), table_name='agent_preferences')
    op.drop_index(op.f('ix_agent_preferences_id'), table_name='agent_preferences')
    op.drop_table('agent_preferences')
    op.drop_index(op.f('ix_research_templates_name'), table_name='research_templates')
    op.drop_index(op.f('ix_research_templates_is_active'), table_name='research_templates')
    op.drop_index(op.f('ix_research_templates_id'), table_name='research_templates')
    op.drop_index(op.f('ix_research_templates_category'), table_name='research_templates')
    op.drop_table('research_templates')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_dismissed'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_deal_type_configs_name'), table_name='deal_type_configs')
    op.drop_index(op.f('ix_deal_type_configs_id'), table_name='deal_type_configs')
    op.drop_table('deal_type_configs')
    op.drop_index(op.f('ix_contract_templates_state'), table_name='contract_templates')
    op.drop_index(op.f('ix_contract_templates_is_active'), table_name='contract_templates')
    op.drop_index(op.f('ix_contract_templates_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_index(op.f('ix_compliance_rule_templates_id'), table_name='compliance_rule_templates')
    op.drop_table('compliance_rule_templates')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_activity_events_tool_name'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_timestamp'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_event_type'), table_name='activity_events')
    op.drop_table('activity_events')
    # ### end Alembic commands ###
