"""Facebook Ads Campaign Management"""
from sqlalchemy import Column, Integer, String, Text, JSON, Boolean, DateTime, ForeignKey, Float
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from app.database import Base


class FacebookCampaign(Base):
    """Facebook ad campaigns generated by AI"""
    __tablename__ = "facebook_campaigns"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)
    property_id = Column(Integer, ForeignKey("properties.id"), nullable=True)

    # Campaign details
    campaign_name = Column(String(255), nullable=False)
    campaign_objective = Column(String(100), nullable=False)  # awareness, traffic, engagement, leads, conversions
    campaign_status = Column(String(50), default="draft")  # draft, active, paused, completed

    # Targeting
    targeting_audience = Column(JSON, nullable=True)  # {age_min, age_max, genders, locations, interests}
    targeting_custom_audiences = Column(JSON, nullable=True)  # list of custom audience IDs
    targeting_lookalike = Column(JSON, nullable=True)  # lookalike audience configs

    # Budget & Schedule
    daily_budget = Column(Float, nullable=True)
    lifetime_budget = Column(Float, nullable=True)
    start_date = Column(DateTime, nullable=True)
    end_date = Column(DateTime, nullable=True)

    # Ad Creatives
    ad_creatives = Column(JSON, nullable=True)  # list of ad creative configs
    ad_copy = Column(JSON, nullable=True)  # primary_text, headline, description
    ad_format = Column(String(50), default="single_image")  # single_image, video, carousel, collection

    # AI Generation Metadata
    source_url = Column(String(500), nullable=True)  # property URL or website analyzed
    generated_by = Column(String(50), default="ai")  # ai, manual, template
    generation_model = Column(String(100), nullable=True)  # claude, gpt-4, etc.

    # Performance Tracking
    campaign_id_meta = Column(String(100), nullable=True)  # Meta Ads campaign ID
    metrics = Column(JSON, nullable=True)  # {impressions, clicks, ctr, spend, conversions, etc.}
    last_synced_at = Column(DateTime, nullable=True)

    # Review Intelligence
    review_insights = Column(JSON, nullable=True)  # extracted from Google reviews
    sentiment_score = Column(Float, nullable=True)  # -1 to 1
    key_phrases = Column(JSON, nullable=True)  # phrases for ad copy

    # Competitor Analysis
    competitor_analysis = Column(JSON, nullable=True)  # competitor ad strategies
    competitor_spend_patterns = Column(JSON, nullable=True)

    # Launch Settings
    meta_access_token = Column(String(500), nullable=True)  # encrypted token
    auto_launch = Column(Boolean, default=False)
    launch_config = Column(JSON, nullable=True)

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    agent = relationship("Agent", back_populates="facebook_campaigns")
    property = relationship("Property", back_populates="facebook_campaigns")


class FacebookAdSet(Base):
    """Ad sets within campaigns"""
    __tablename__ = "facebook_ad_sets"

    id = Column(Integer, primary_key=True, index=True)
    campaign_id = Column(Integer, ForeignKey("facebook_campaigns.id"), nullable=False)

    ad_set_name = Column(String(255), nullable=False)
    targeting = Column(JSON, nullable=True)
    optimization_goal = Column(String(100), nullable=True)  # conversions, clicks, impressions
    billing_event = Column(String(50), nullable=True)  # impressions, clicks
    bid_strategy = Column(String(50), nullable=True)  # lowest_cost, target_cost

    daily_budget = Column(Float, nullable=True)
    start_time = Column(DateTime, nullable=True)
    end_time = Column(DateTime, nullable=True)

    ad_set_id_meta = Column(String(100), nullable=True)
    status = Column(String(50), default="active")

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))


class FacebookCreative(Base):
    """Ad creative assets"""
    __tablename__ = "facebook_creatives"

    id = Column(Integer, primary_key=True, index=True)
    campaign_id = Column(Integer, ForeignKey("facebook_campaigns.id"), nullable=False)

    creative_name = Column(String(255), nullable=False)
    creative_format = Column(String(50), nullable=False)  # image, video, carousel, collection

    # Asset URLs
    image_url = Column(String(500), nullable=True)
    video_url = Column(String(500), nullable=True)
    carousel_items = Column(JSON, nullable=True)  # list of carousel assets

    # Copy
    primary_text = Column(Text, nullable=True)
    headline = Column(String(255), nullable=True)
    description = Column(String(255), nullable=True)
    call_to_action = Column(String(50), nullable=True)  # shop_now, learn_more, sign_up, etc.

    # Dynamic Creative
    dynamic_creative_options = Column(JSON, nullable=True)  # multiple images, texts, titles

    creative_id_meta = Column(String(100), nullable=True)
    status = Column(String(50), default="active")

    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))


class MarketResearch(Base):
    """Market research for Facebook ad targeting"""
    __tablename__ = "market_research"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)

    research_name = Column(String(255), nullable=False)
    market_location = Column(JSON, nullable=True)  # {cities, regions, countries}
    market_niche = Column(String(255), nullable=True)  # real estate, luxury, rental, etc.

    # Audience Insights
    audience_size_estimate = Column(Integer, nullable=True)
    audience_demographics = Column(JSON, nullable=True)  # age, gender, income, education
    audience_interests = Column(JSON, nullable=True)  # top interests and behaviors

    # Keyword Opportunities
    keywords = Column(JSON, nullable=True)  # relevant keywords for targeting
    keyword_search_volume = Column(JSON, nullable=True)

    # Positioning Data
    market_positioning = Column(JSON, nullable=True)  # unique value props, messaging angles
    competitor_positioning = Column(JSON, nullable=True)

    # Market Trends
    seasonal_trends = Column(JSON, nullable=True)
    price_sensitivity = Column(JSON, nullable=True)

    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Relationships
    agent = relationship("Agent")


class CompetitorAnalysis(Base):
    """Competitor ad intelligence"""
    __tablename__ = "competitor_analyses"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)

    competitor_name = Column(String(255), nullable=True)
    competitor_domain = Column(String(500), nullable=True)

    # Ad Intelligence
    active_ads_count = Column(Integer, default=0)
    ad_spend_estimate = Column(Float, nullable=True)  # monthly estimated spend
    ad_frequency = Column(Float, nullable=True)  # avg ads per week

    # Creative Strategies
    top_performing_creatives = Column(JSON, nullable=True)  # top ad creative examples
    creative_themes = Column(JSON, nullable=True)  # themes and patterns
    copy_patterns = Column(JSON, nullable=True)  # common copy structures

    # Targeting Intelligence
    suspected_audiences = Column(JSON, nullable=True)  # inferred targeting
    targeting_patterns = Column(JSON, nullable=True)

    # Landing Pages
    landing_pages = Column(JSON, nullable=True)  # {url, headline, cta}
    funnel_structure = Column(JSON, nullable=True)

    analyzed_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Relationships
    agent = relationship("Agent")


class ReviewIntelligence(Base):
    """Customer sentiment extracted from reviews"""
    __tablename__ = "review_intelligence"

    id = Column(Integer, primary_key=True, index=True)
    agent_id = Column(Integer, ForeignKey("agents.id"), nullable=False)
    property_id = Column(Integer, ForeignKey("properties.id"), nullable=True)

    source = Column(String(100), nullable=False)  # google, yelp, zillow, realtor.com
    source_url = Column(String(500), nullable=True)

    # Sentiment Analysis
    overall_sentiment = Column(String(20), nullable=True)  # positive, neutral, negative
    sentiment_score = Column(Float, nullable=True)  # -1.0 to 1.0
    sentiment_distribution = Column(JSON, nullable=True)  # {positive: X%, negative: Y%}

    # Extracted Insights
    key_phrases = Column(JSON, nullable=True)  # phrases for ad copy
    pain_points = Column(JSON, nullable=True)  # customer pain points
    selling_points = Column(JSON, nullable=True)  # positive themes
    questions_asked = Column(JSON, nullable=True)  # common questions

    # Review Stats
    total_reviews = Column(Integer, default=0)
    average_rating = Column(Float, nullable=True)
    rating_distribution = Column(JSON, nullable=True)  # 5-star: X, 4-star: Y, etc.

    # Ad Copy Recommendations
    recommended_hooks = Column(JSON, nullable=True)  # attention-grabbing opening lines
    recommended_ctas = Column(JSON, nullable=True)  # effective calls-to-action
    recommended_themes = Column(JSON, nullable=True)  # messaging themes

    extracted_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Relationships
    agent = relationship("Agent")
    property = relationship("Property")


# Update Agent and Property models to include relationships
from app.models.agent import Agent
from app.models.property import Property

# Add relationships (these would be added to the respective model files)
Agent.facebook_campaigns = relationship("FacebookCampaign", back_populates="agent")
Property.facebook_campaigns = relationship("FacebookCampaign", back_populates="property")
