"""Follow-up sequence models — automated multi-channel drip campaigns."""

from sqlalchemy import Column, Integer, String, DateTime, Text, Boolean, Float, ForeignKey, Enum as SAEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import enum

from app.database import Base


class SequenceStatus(str, enum.Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class TouchChannel(str, enum.Enum):
    EMAIL = "email"
    SMS = "sms"
    CALL = "call"
    POSTCARD = "postcard"
    RINGLESS_VM = "ringless_vm"


class TouchStatus(str, enum.Enum):
    PENDING = "pending"
    SCHEDULED = "scheduled"
    SENT = "sent"
    DELIVERED = "delivered"
    OPENED = "opened"
    REPLIED = "replied"
    FAILED = "failed"
    SKIPPED = "skipped"


class LeadTemperature(str, enum.Enum):
    HOT = "hot"
    WARM = "warm"
    COLD = "cold"
    DEAD = "dead"


class FollowUpSequence(Base):
    __tablename__ = "follow_up_sequences"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    contact_id = Column(Integer, ForeignKey("contacts.id"), nullable=True, index=True)
    property_id = Column(Integer, ForeignKey("properties.id"), nullable=True, index=True)

    # Lead info (can work without existing contact)
    lead_name = Column(String(255))
    lead_email = Column(String(255))
    lead_phone = Column(String(50))
    lead_source = Column(String(100))  # zillow, realtor.com, referral, website, cold
    lead_temperature = Column(SAEnum(LeadTemperature), default=LeadTemperature.WARM)

    # Sequence config
    template_name = Column(String(100), default="default")  # which sequence template
    status = Column(SAEnum(SequenceStatus), default=SequenceStatus.ACTIVE, index=True)
    current_step = Column(Integer, default=0)
    total_steps = Column(Integer, default=0)

    # Engagement tracking
    emails_sent = Column(Integer, default=0)
    emails_opened = Column(Integer, default=0)
    sms_sent = Column(Integer, default=0)
    calls_made = Column(Integer, default=0)
    postcards_sent = Column(Integer, default=0)
    replies_received = Column(Integer, default=0)
    engagement_score = Column(Float, default=0.0)  # 0-100

    # Timing
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    paused_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    next_touch_at = Column(DateTime(timezone=True), nullable=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    touches = relationship("SequenceTouch", back_populates="sequence", cascade="all, delete-orphan", order_by="SequenceTouch.step_number")


class SequenceTouch(Base):
    __tablename__ = "sequence_touches"

    id = Column(Integer, primary_key=True, index=True)
    sequence_id = Column(Integer, ForeignKey("follow_up_sequences.id", ondelete="CASCADE"), nullable=False, index=True)
    step_number = Column(Integer, nullable=False)

    # What to do
    channel = Column(SAEnum(TouchChannel), nullable=False)
    delay_days = Column(Integer, nullable=False)  # days after sequence start
    subject = Column(String(500), nullable=True)  # email subject
    message = Column(Text, nullable=True)  # generated by Claude
    ai_generated = Column(Boolean, default=True)

    # Status
    status = Column(SAEnum(TouchStatus), default=TouchStatus.PENDING, index=True)
    scheduled_at = Column(DateTime(timezone=True), nullable=True)
    sent_at = Column(DateTime(timezone=True), nullable=True)
    delivered_at = Column(DateTime(timezone=True), nullable=True)
    opened_at = Column(DateTime(timezone=True), nullable=True)
    replied_at = Column(DateTime(timezone=True), nullable=True)
    error_message = Column(Text, nullable=True)

    # External IDs
    external_id = Column(String(255), nullable=True)  # resend message ID, Lob mail ID, etc.

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    sequence = relationship("FollowUpSequence", back_populates="touches")
